apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: px
  namespace: {{ namespace }}
  labels:
    app: px
spec:
  replicas: {{ px.replica_count }}
  selector:
    matchLabels:
      app: px
  template:
    metadata:
      labels:
        app: px
    spec:
      containers:
      - name: px-memcache
        image: "{{ px_memcache.image_name }}:{{ px_memcache.image_tag }}"
        imagePullPolicy: IfNotPresent
        ports:
        - name: main
          containerPort: 11211
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 11211
        livenessProbe:
          tcpSocket:
            port: 11211
        resources:
          limits:
            memory: {{ px_memcache.resources.limits.memory }}
            cpu: {{ px_memcache.resources.limits.cpu }}
          requests:
            memory: {{ px_memcache.resources.requests.memory }}
            cpu: {{ px_memcache.resources.limits.cpu }}
      - name: px-php
        image: "{{ px_php.image_name }}:{{ px_php.image_tag }}"
        imagePullPolicy: IfNotPresent
        ports:
        - name: main
          containerPort: 9000
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 9000
        livenessProbe:
          tcpSocket:
            port: 9000
        resources:
          limits:
            memory: {{ px_php.resources.limits.memory }}
            cpu: {{ px_php.resources.limits.cpu }}
          requests:
            memory: {{ px_php.resources.requests.memory }}
            cpu: {{ px_php.resources.limits.cpu }}
        volumeMounts:
        - name: px-env
          mountPath: /var/www/px-profi/env.php
          subPath: env.php
        - name: px-api
          mountPath: /var/www/px-profi/protected/config/api.php
          subPath: api.php
      - name: px-nginx
        image: "{{ px_nginx.image_name }}:{{ px_nginx.image_tag }}"
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: php
          containerPort: 8900
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        volumeMounts:
        - name: px-profi
          mountPath: /etc/nginx/conf.d/px-profi.conf
          subPath: px-profi.conf
        - name: px-php
          mountPath: /etc/nginx/conf.d/hosts/px-php.inc
          subPath: px-php.inc
        resources:
          limits:
            memory: {{ px_nginx.resources.limits.memory }}
            cpu: {{ px_nginx.resources.limits.cpu }}
          requests:
            memory: {{ px_nginx.resources.requests.memory }}
            cpu: {{ px_nginx.resources.limits.cpu }}
      imagePullSecrets:
      - name: {{ registry_credential_secret }}
      volumes:
      - name: px-php
        configMap:
          name: px-php
      - name: px-profi
        configMap:
          name: px-profi
      - name: px-env
        configMap:
          name: px-env
      - name: px-api
        configMap:
          name: px-api