apiVersion: v1
kind: ConfigMap
metadata:
  name: px-fastcgi-{{ release_name }}
  namespace: {{ namespace }}
  labels:
    app: px-{{ release_name }}
data:
  fastcgi.conf: |
    gzip on;
    set $_uid_ip "";
    set $_cond "";
    if ($arg_egab_uid ~ "^([A-z0-9]{32})(\d+)$") {
        set $_uid_uid $1;
        set $_uid_ip $2;
        set $_cond "A";
    }

    if ($remote_addr ~ "^(\d+)+\.(\d+)+\.(\d+)+\.(\d+)+$") {
        set $_ip "$1$2$3$4";
    }

    if ($_uid_ip = $_ip) {
        set $_cond "${_cond}B";
    }

    if ($_cond = "AB") {
        add_header Set-Cookie "uid=${_uid_uid}; expires=Thu, 31-Dec-37 23:55:55 GMT; path=/";
        set $uid $_uid_uid;
    }

    if ($cookie_uid = "") {
        add_header Set-Cookie "uid=${uid}; expires=Thu, 31-Dec-37 23:55:55 GMT; path=/";
    }

    fastcgi_pass    127.0.0.1:9000;

    #fastcgi_index   index.php;
    fastcgi_connect_timeout 5;
    fastcgi_buffer_size 64k;
    fastcgi_buffers 8 32k;
    fastcgi_param   DOCUMENT_ROOT   /$pxdir/htdocs;
    fastcgi_param   SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param   PATH_INFO       $fastcgi_script_name;
    fastcgi_param   PX_UID       $uid;
    #fastcgi_param   PX_EXTERNAL $px_external;
    fastcgi_param   PX_META "";
    fastcgi_param   PX_USER_COUNTRY $country;
    fastcgi_param   PX_GEO_REGION $geo_region;
    fastcgi_param   PX_CITY $city;
    fastcgi_param   PX_REQUEST_ID $http_request_id;
    include         fastcgi_params;

    ssi               on;
    ssi_silent_errors on;

    add_header X-Cache         $upstream_cache_status;
    add_header X-Cache-Control $upstream_http_cache_control;

    fastcgi_cache_methods   GET HEAD;
    fastcgi_cache           PX_PROFI;

    fastcgi_cache_min_uses  1;
    fastcgi_cache_lock      on;
    fastcgi_cache_use_stale error timeout invalid_header updating http_500 http_503;
    fastcgi_cache_background_update on;
