apiVersion: v1
kind: Service
metadata:
  name: px-ngi
  namespace: {{ namespace }}
  labels:
    app: px
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 8900
    targetPort: 8900
    protocol: TCP
    name: php
  selector:
    app: px