---
- name: Copy kubernetes.repo
  copy:
    src: "{{ role_path }}/files/kubernetes.repo"
    dest: /etc/yum.repos.d/kubernetes.repo

- name: Disable selinux
  command: setenforce 0
  ignore_errors: yes

- name: Change /etc/selinux/config
  replace:
    dest: /etc/selinux/config
    regexp: '^SELINUX=enforcing$'
    replace: 'SELINUX=permissive'

- name: Copy /etc/sysctl.d/k8s.conf
  copy:
    src: "{{ role_path }}/files/k8s.conf"
    dest: /etc/sysctl.d/k8s.conf

- name: sysctl --system
  command: sysctl --system

- name: Install kubelet, kubeadm, kubectl
  yum:
    name: "{{ packages }}"
    disable_excludes: kubernetes
  vars:
    packages:
    - "kubelet-{{ k8s_version }}"
    - "kubeadm-{{ k8s_version }}"
    - "kubectl-{{ k8s_version }}"

- name: Start kubelet
  systemd:
    state: started
    name: kubelet

- name: Enable kubelet
  systemd:
    name: kubelet
    enabled: yes
