- name: Get token from master
  hosts: init-master
  become: yes
  become_method: sudo
  roles:
    - get-token

- name: Add new worker to cluster
  hosts:
  become: yes
  become_method: sudo
  roles:
    - swap
    - ntpdate
    - docker
    - kubernetes
    - worker

