---
- name: Copy kubernetes.repo
  copy:
    src: "{{ role_path }}/files/kubernetes.repo"
    dest: /etc/yum.repos.d/kubernetes.repo

- name: Disable selinux
  command: setenforce 0
  ignore_errors: yes

- name: Change /etc/selinux/config
  replace:
    dest: /etc/selinux/config
    regexp: '^SELINUX=enforcing$'
    replace: 'SELINUX=permissive'

- name: Install kubelet, kubeadm, kubectl
  yum:
    name: "{{ packages }}"
    disable_excludes: kubernetes
  vars:
    packages:
    - kubelet
    - kubeadm
    - kubectl

- name: Start kubelet
  systemd:
    state: started
    name: kubelet

- name: Enable kubelet
  systemd:
    name: kubelet
    enabled: yes
