---
- name: Install requiered packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: Add docker-ce repository
  yum_repository:
    name: docker-ce
    description: docker-ce
    baseurl: https://download.docker.com/linux/centos/docker-ce.repo 

- name: Install docker-ce
  yum:
    name: docker-ce
    state: present
